#region License

//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

#endregion

namespace Endjin.Templify.Specifications.MSBuild
{
	using Endjin.Templify.Domain.Contracts.Tasks;
	using Endjin.Templify.MSBuild;

	using Machine.Specifications;
	using Machine.Specifications.AutoMocking.Rhino;

	public abstract class specification_for_create_package_msbuild_task : Specification<CreatePackage>
	{
		protected static IPackageCreatorTasks the_package_creator_tasks;

		Establish context = () =>
			{
				the_package_creator_tasks = DependencyOf<IPackageCreatorTasks>();
			};
	}

	[Subject(typeof(CreatePackage))]
	public class when_the_create_package_msbuild_task_is_executed : specification_for_create_package_msbuild_task
	{
		It should_
	}
}